import streamlit as st

st.set_page_config(page_title="Terms · ChatTFT", page_icon="♟", layout="centered")

st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Rajdhani:wght@600;700&family=Inter:wght@300;400;500&display=swap');
    .stApp { background-color: #080c14; color: #c9d1e0; font-family: 'Inter', sans-serif; }
    #MainMenu { visibility: hidden; }
    footer { visibility: hidden; }
    header { visibility: hidden; height: 0 !important; min-height: 0 !important; }
    [data-testid="stSidebarNav"] { display: none !important; }
    [data-testid="stSidebar"] { display: none !important; }
    [data-testid="stSidebarCollapsedControl"] { display: none !important; }
    .block-container { padding: 3rem 2rem; max-width: 760px; }
</style>
""", unsafe_allow_html=True)
 
st.markdown("""
<div style="margin-bottom:32px">
    <div style="font-family:'Rajdhani',sans-serif;font-size:28px;font-weight:700;color:#ffffff;letter-spacing:2px">
        ♟ Chat<span style="color:#c89b3c">TFT</span>
        <span style="font-size:14px;color:#4a5568;font-weight:400;letter-spacing:1px;margin-left:12px">TERMS OF USE</span>
    </div>
</div>
""", unsafe_allow_html=True)

terms_data = [
    ("1. AFFILIATION", "ChatTFT is an independent fan project and is not affiliated with, endorsed by, or in any way officially connected to Riot Games, Inc. Teamfight Tactics, TFT, League of Legends, and all associated marks, logos, and content are trademarks or registered trademarks of Riot Games, Inc."),
    ("2. DATA SOURCE", "Match and player data is retrieved through the Riot Games API. Data accuracy, completeness, and availability depend on Riot's API and are not guaranteed. Cached data may be up to 24 hours old."),
    ("3. AI-GENERATED CONTENT", "Coaching insights and chat responses are generated by a large language model (Groq / Meta LLaMA 3.3). This content may be factually incorrect, outdated, or contextually inappropriate. It does not constitute professional esports or gaming coaching and is provided for entertainment and educational purposes only."),
    ("4. PRIVACY & DATA", "To use this service you provide a public Riot Game Name and tag. We store your PUUID (a Riot-assigned identifier) and public match data solely to cache results and improve performance. We do not collect email addresses, payment information, or any personal information beyond what is publicly available through the Riot API. You may request deletion of your cached data at any time by contacting us."),
    ("5. LIMITATION OF LIABILITY", 'ChatTFT is provided "as is" without warranty of any kind, express or implied. We make no representations regarding the accuracy, reliability, or completeness of any information provided. We are not liable for any loss, damage, rank decline, or negative outcome resulting from reliance on information, AI coaching, or meta analysis provided by this tool.'),
    ("6. CHANGES", "These terms may be updated at any time without prior notice. Continued use of the service following any such update constitutes your acceptance of the revised terms. We encourage you to review this page periodically."),
]

for title, body in terms_data:
    st.markdown(f"""
    <div style="background:linear-gradient(145deg,#0d1221,#0a0e1a);border:1px solid #1a2235;
                border-radius:12px;padding:20px 24px;margin-bottom:16px">
        <div style="font-family:'Rajdhani',sans-serif;font-size:11px;font-weight:700;
                    letter-spacing:3px;color:#c89b3c;text-transform:uppercase;margin-bottom:10px">{title}</div>
        <div style="font-size:13px;color:#8a9bb5;font-family:'Inter',sans-serif;line-height:1.8">{body}</div>
    </div>
    """, unsafe_allow_html=True)

st.markdown("<div style='height:20px'></div>", unsafe_allow_html=True)
st.page_link("app.py", label="← Back to ChatTFT", icon="♟")